title: Asahi Linux Stuff
description: A Documentation Page about Asahi Linux
theme: minimal-mistakes-jekyll

url: https://mmistakes.github.io/minimal-mistakes/

aux_links:
  Asahi Linux: https://asahilinux.org/
